syntax = "proto3";

package coordinator.v1;

import "google/protobuf/timestamp.proto";
import "google/protobuf/struct.proto";

// -------------- Dataset Service -------------

// service related to dataset, and anything talk to filemetrix
service DatasetService {
  // Lazily retrieve file hierarchy or file info for a dataset
  rpc BrowseDataset(BrowseDatasetRequest)
    returns (stream BrowseDatasetResponse);

  // this is design to go to the source to lazily get the files
  // In reality this is specifially exposed because we have datahugger-ng to do file fetching
  rpc BrowseDatasetByUrl(BrowseDatasetByUrlRequest)
    returns (stream BrowseDatasetResponse);

  // rpc DownloadFile(DownloadFileRequest)
  //   returns (stream FileChunk);
}


// structure partially borrow from unix file handler
message FileEntry {
  // download url
  optional string download_url = 1;
  // abs path, root from dataset, include the basename.
  string path = 2;
  // no matter basename or path ended with '/' or not, this is the only source of truth on 
  // it is a file or dir
  bool is_dir = 3;
  // size in bytes
  uint64 size_bytes = 4;
  // mime_type, unset if unknown
  optional string mime_type = 5;
  // checksum type
  optional string checksum_type = 6;
  // checksum
  optional string checksum = 7;

  // latest time the file is modified
  google.protobuf.Timestamp modified_at = 8;
}

message BrowseDatasetRequest {
  // uuid
  string uuid = 1;
  // Data repo identifier by url (opaque to client)
  string url_datarepo = 2;
  // Dataset identifier (opaque to client)
  string id_dataset = 3;
}

message BrowseDatasetByUrlRequest {
  string url = 1;
}

message BrowseDatasetResponse {
  // Server MUST send dataset_info as first message at INIT phase
  // Server MUST not send any more messages after COMPLETE phase
  enum BrowsePhase {
    PHASE_UNSPECIFIED = 0;
    PHASE_INIT = 1;
    PHASE_BROWSING = 2;
    PHASE_COMPLETED = 3;
  }

  BrowsePhase phase = 1;

  oneof event {
    // summury or basic metadata, send once at PHASE_INIT
    DatasetInfo dataset_info = 2;
    // entry entity of file, send at PHASE_BROWSING
    FileEntry file_entry = 3;
    // progress for how much is done already
    BrowseProgress progress = 4;
    // if any error happing when browsing
    BrowseError error = 5;
    // complete signal
    BrowseComplete complete = 6;
  }
}

message DatasetInfo {
  string url_datarepo = 1;
  string id_dataset = 2;
  string description = 3;

  optional uint64 total_files = 4;
  optional uint64 total_size_bytes = 5;

  google.protobuf.Timestamp created_at = 6;
  google.protobuf.Timestamp updated_at = 7;

  map<string, string> tags = 8;
}

message FileChunk {
  // which file this chunk belongs to, abs path, root from dataset, include the basename.
  string path = 1;       
  // actual content bytes
  bytes data = 2;        
}


message BrowseProgress {
  uint64 files_scanned = 1;
  uint64 bytes_scanned = 2;

  // 0-100
  uint32 percent = 3;
  // path of file in processing 
  optional string path = 4;
}

message BrowseError {
  enum ErrorCode {
    // UNKNOWN at the moment cover most of errors, more specific error type will be added 
    // when it is clear on which errors might happen.
    UNKNOWN = 0;
    // DATASET is not available, for example, havester create the entry but the data repo might offline etc.
    INVALID_DATASET = 1;
    UNAVAILABLE_FILEMETRIX = 2;
    UNAVAILABLE_FILE = 3;
    // IO_ERROR
    // TIMEOUT (for single file or for one dataset??)
  }

  ErrorCode code = 1;
  string message = 2;

  // path of file under processing where error raised
  optional string path = 3;
  // if fatal bail the browse process, otherwise can continue on other files.
  bool fatal = 4;
}

message BrowseComplete {
  uint64 total_files = 1;
  uint64 total_size_bytes = 2;

  bool success = 3;
  google.protobuf.Timestamp finish_at = 4;
}

// -------------- End of Dataset Service -------------

// -------------- Start of Tool Service --------------
// this is what response to client about the vre entity it can utilize.
message ToolMeta {
  // id in the tool registry
  string id = 1;
  string version = 2;
}

message BrowseToolsRequest {}
message BrowseToolsResponse {}

message GetToolRequest {}
message ToolResponse {
  ToolMeta tool = 1;
}

message FindToolsRequest {
  repeated FileEntry files = 2;
}
// Find Tools response include the tool response and the state of the stream
message FindToolsResponse {
  repeated ToolMeta tools = 1;
}

// the tool service as in front of tool-registry DB, this actually can be the packaging hub.
service ToolService {
  // Get a specific tool by id
  rpc GetTool(GetToolRequest) returns (ToolResponse); 

  // Find tools from the file list input provided, and maybe some information from user profile. 
  rpc FindTools(FindToolsRequest) returns (FindToolsResponse);

  rpc BrowseTools(BrowseToolsRequest)
    returns (stream BrowseToolsResponse);
}

// -------------- End of Tool Service --------------

// -------------- Start of Dataplayer Service --------------
// Tool type here is of tool artifact which is running in the real machine (include local on wasm/js or even in **desktop**).

// the lightweight tool do not need resources can be always ready. 
// the tool that need resource preparing, start frond preparing, and end with the resource being dropped
message ToolStatus {
  enum State {
    PREPARING = 0;
    reserved 1, 2, 3, 4;
    READY = 8;
    DROPPED = 9;
  }

  string log = 1;
  State state = 2;
}

// XXX: this is already an abstract with assumption that the tool need and only need files as input to start.
// But in fact, some tool need config files that is independent of data files passed in.
// We may also want to extend this as a tool can be a combination of multiple tool such as resource provider tool. 
// This interface high likely will be full re-definded.
message LaunchToolRequest {
  string tool_id = 1;
  map<string, FileEntry> slots_mapping = 2;
}

message User_Id {
  string inner = 1;
}

message ToolHandler {
  ToolStatus state = 1;
  User_Id owner = 2;
  string id = 3;
}

message LaunchToolResponse {
  string handler_id = 1;
}

message MonitorStatusRequest {
  string id = 1;
}

message MonitorStatusResponse {
  ToolStatus status = 1;
}

message GetStatusRequest {
  string id = 1;
}
message GetStatusResponse {
  ToolStatus status = 1;
}


message DropRequest {
  string id = 1;
}
message DropResponse {
  string ack = 1;
}

message QueryUserRequest {
  User_Id user_id = 1;
}
message QueryUserResponse {
  repeated ToolHandler ths = 1;
}

message GetArtifactRequest {
  string handler_id = 1;
}

message HostedTool {
  string callback_url = 1;
}

message EoscInlineTool {
  string callback_url = 1;
}

message DesktopTool {
  // ?? how??
}

message GetArtifactResponse {
  oneof entry_point {
    EoscInlineTool eosc_inline = 1;
    HostedTool hosted = 2;
  }
}

// this is the service in front of dispatcher or say all other real vre artifact.
service DataplayerService {
  // launch the tool
  rpc LaunchTool(LaunchToolRequest) returns (LaunchToolResponse); 

  // find all instance of a user, kv table search, in-memory if empharpha or using sqlite to FS if persistence needed.
  rpc Query(QueryUserRequest) returns (QueryUserResponse);

  // Get the artifact from id.
  rpc GetArtifact(GetArtifactRequest) returns (GetArtifactResponse);

  // monitoring the status of one running session
  rpc MonitorStatus(MonitorStatusRequest) returns (stream MonitorStatusResponse);

  rpc GetStatus(GetStatusRequest) returns (GetStatusResponse);

  // ??? who should drop? vre call drop or from edc system call drop?
  // Is the use case always after the control move to vre, it never goes back to eosc?
  rpc Drop(DropRequest) returns (DropResponse);
}

// -------------- End of Dataplayer Service --------------

